version: "3.1"

services:
    web:
        image: nginx:alpine
        volumes:
            - ./:/app/docker
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 2222:80

    app:
        build:
            context: ../
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ../:/app
            - ./php/php.ini:/usr/local/etc/php/php.ini
