name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            php-versions: ['7.4', '8.0']
        name: PHP ${{ matrix.php-versions }} Test

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: composer:v2, phpunit:v9

            - name: Install Dependencies
              run: composer install

            - name: PHPUnit Tests
              run: vendor/bin/phpunit
